name: Deploy WordPress Theme

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build theme
        run: node build.js --silent

      - name: Debug build output
        run: |
          ls -la public_html/wp-content/themes/watertowncommunitygardens/
          du -sh public_html/wp-content/themes/watertowncommunitygardens/
          find public_html/wp-content/themes/watertowncommunitygardens/ -type f | wc -l
          ls -la public_html/wp-content/themes/watertowncommunitygardens/js/
          cat public_html/wp-content/themes/watertowncommunitygardens/style.css | wc -l

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /var/www/html/wp-content/themes/watertowncommunitygardens/
            mkdir -p /var/www/html/wp-content/themes/watertowncommunitygardens/js/

      - name: Copy theme files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          source: "public_html/wp-content/themes/watertowncommunitygardens/*"
          target: "/var/www/html/wp-content/themes/watertowncommunitygardens/"
          overwrite: true
          debug: true

      - name: Verify files on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            ls -la /var/www/html/wp-content/themes/watertowncommunitygardens/
            du -sh /var/www/html/wp-content/themes/watertowncommunitygardens/
            find /var/www/html/wp-content/themes/watertowncommunitygardens/ -type f | wc -l
            ls -la /var/www/html/wp-content/themes/watertowncommunitygardens/js/
            head -n 10 /var/www/html/wp-content/themes/watertowncommunitygardens/style.css || echo "Cannot read style.css"
