name: Deploy WordPress Theme

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build theme
        run: node build.js --silent

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /var/www/html/wp-content/themes/watertowncommunitygardens/

      - name: Copy theme files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          source: "public_html/wp-content/themes/watertowncommunitygardens/*"
          target: "/var/www/html/wp-content/themes/watertowncommunitygardens/"
          overwrite: true
